# Generated by Django 5.0 on 2023-12-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commande_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default=500, max_length=200),
            preserve_default=False,
        ),
    ]
